2021-07-15 13:25:57,651 ERROR: Exception on /predict [GET] [in /Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/routes.py", line 124, in predict
    if user is None:
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/jinja2/environment.py", line 1067, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: predict.html
2021-07-15 13:26:19,227 ERROR: Exception on /predict [GET] [in /Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/routes.py", line 124, in predict
    if user is None:
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/jinja2/environment.py", line 1067, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: predict.html
2021-07-15 13:28:15,469 INFO: Microblog startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:54]
2021-07-16 08:35:52,442 INFO: Microblog startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:67]
2021-07-16 08:36:00,538 ERROR: Exception on /index [GET] [in /Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/main/main.py", line 30, in index
    return render_template('main_bp/index.html', title='Home Page', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/jinja2/environment.py", line 1067, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/Rafa/opt/anaconda3/envs/NLP_Env/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main_bp/index.html
2021-07-16 08:38:03,934 INFO: Microblog startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:67]
2021-07-16 08:38:58,118 INFO: Microblog startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:67]
2021-07-18 19:35:59,254 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:71]
2021-07-18 19:36:11,629 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:71]
2021-07-18 19:36:23,527 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:71]
2021-07-18 19:41:22,650 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:74]
2021-07-18 19:43:50,102 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:74]
2021-07-18 19:44:09,296 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:74]
2021-07-18 19:44:24,197 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:74]
2021-07-18 19:44:56,875 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:74]
2021-07-18 19:45:16,783 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:74]
2021-07-18 19:47:35,319 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:74]
2021-07-18 19:49:04,620 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:74]
2021-07-18 19:57:28,719 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:74]
2021-07-18 19:57:36,837 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:74]
2021-07-18 20:00:39,078 INFO: Flit_beta startup [in /Users/Rafa/Desktop/Learning/Web/Flask/web_app/app/__init__.py:74]
